<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Skrill_MoneybookersPsp
 * @copyright  Copyright (c) 2012 Skrill Holdings Ltd. (http://www.skrill.com)
 */

$_code = $this->getMethodCode();
$_img = $this->getPaymentImageSrc($_code);
$_formId = Mage::helper('moneybookerspsp')->getFormPlaceholderId($_code);
?>
<fieldset class="form-list" id="payment_form_<?php echo $_code ?>" style="display: none;">
<script type="text/javascript">
    payment.isMoneybookersPspDataValid = [];
</script>
<?php $_iframeSrcUrl = $this->getMethod()->getWPFRegisterFormUrl(); ?>
<iframe id="<?php echo $_formId ?>" allowtransparency="true" frameborder="0" scrolling="no" src="<?php echo $_iframeSrcUrl ?>"></iframe>
</fieldset>
<?php if ($_img): ?>
    <div class="moneybookers_method_logo">
        <img src="<?php echo $_img ?>" alt="" /><br />
    </div>
<?php endif; ?>