<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Skrill_MoneybookersPsp
 * @copyright  Copyright (c) 2012 Skrill Holdings Ltd. (http://www.skrill.com)
 */

$order = Mage::registry('current_order');
$url = $order->getPayment()->getMethodInstance()->getWPFDebitFormUrl();
$redirect = (integer)Mage::getConfig()->getNode("global/customsettings/redirect");
?>
<?php if ($url): ?>
<?php 

if ($redirect === 1) : 
    header('Location: ' . $url);
    exit();
endif; ?>

<div class="page-head">
    <h3><?php echo Mage::helper('moneybookerspsp')->__('Please pay your order now') ?></h3>
</div>
<iframe src="<?php echo $url ?>" allowtransparency="true" frameborder="0" scrolling="no" style="width:100%; height:600px; border:none;"></iframe>
<?php else: ?>
<div class="page-head">
    <h3><?php echo Mage::helper('moneybookerspsp')->__('An error occured while trying to connect to the payment service provider') ?></h3>
</div>
<?php endif; ?>