<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Skrill_MoneybookersPsp
 * @copyright  Copyright (c) 2012 Skrill Holdings Ltd. (http://www.skrill.com)
 */
?>
<?php $_formPrefix = Mage::helper('moneybookerspsp')->getFormPlaceholderPrefix(); ?>
<div>
<?php echo $this->__('Transaction failed. Please check your account data.') ?>
</div>
<a id="moneybookerspsp_change_account_data" href="#" onclick="mbPspChangeAccountData();"><?php echo $this->__("Change Account Data")?></a>
<script type="text/javascript">
    parent.payment.isMoneybookersPspDataValid[parent.payment.currentMethod] = false;
    parent.checkout.setLoadWaiting(false);

    function mbPspChangeAccountData(){
        var method = parent.payment.currentMethod;
        var element = parent.document.getElementById('<?php echo $_formPrefix?>'+method);
        var url = element.src.split('#')[0];
        element.src = url;
    }
</script>