<?php
/*------------------------------------------------------------------------
 # SM Listing Tabs - Version 2.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$helper = Mage::helper('listingtabs/data');
$list = $this->_getList();

if (!empty($list)) {

	$import_str = "";
	$jsHelper = Mage::helper('core/js');
	// jquery has not added yet
	if (!defined('MAGENTECH_JQUERY') && (int)$this->_getConfig('include_jquery')) {
		// if module allowed jquery.
		$import_str .= $jsHelper->includeSkinScript('sm/listingtabs/js/jquery-1.8.2.min.js');
		$import_str .= $jsHelper->includeSkinScript('sm/listingtabs/js/jquery-noconflict.js');
		define('MAGENTECH_JQUERY', 1);
	}
	echo $import_str;


	$module_id = $this->_moduleID();
	$tag_id = 'sm_listing_tabs_' . rand() . time();
	$class_ltabs = 'ltabs00-' . $this->_getConfig('nbi_column1', 4) . ' ltabs01-' . $this->_getConfig('nbi_column1', 3) . ' ltabs02-' . $this->_getConfig('nbi_column2', 3) . ' ltabs03-' . $this->_getConfig('nbi-column3', 2) . ' ltabs04-' . $this->_getConfig('nbi-column4', 1)
	?>

	<div id="<?php echo $tag_id; ?>" class="sj-listing-tabs listing-tabs-slider first-load">
		<?php if ($this->_getConfig('listingtabs_title_text')) { ?>
			<div class="tab-listing-title">
				<?php echo $this->_getConfig('listingtabs_title_text', 'Tab Listing'); ?>
			</div>
		<?php } ?>
		
		<div class="ltabs-wrap ">
			<div class="ltabs-tabs-container" data-delay="<?php echo $this->_getConfig('delay', 300); ?>"
			     data-duration="<?php echo $this->_getConfig('duration', 600); ?>"
			     data-effect="<?php echo $this->_getConfig('effect'); ?>"
			     data-ajaxurl="<?php echo Mage::getBaseUrl() . 'listingtabs/index/ajax'; ?>"
			     data-modid="<?php echo $tag_id; ?>">
				<!--Begin Tabs-->
				<?php include('default_tabs.phtml'); ?>
			</div>
			
			<?php $pretext = $this->_getConfig('pretext');if (!empty($pretext)) {?>
				<div class="pre-text"><?php echo $this->_getConfig('pretext'); ?></div>
			<?php } ?>
			<!-- End Tabs-->
			<div class="ltabs-items-container slider-tabl"><!--Begin Items-->

				<?php foreach ($list as $items) {
					$child_items = isset($items->child) ? $items->child : '';
					$cls_device = $class_ltabs;
					$cls_animate = $this->_getConfig('effect');
					$cls = (isset($items->sel) && $items->sel == "sel") ? ' ltabs-items-selected ltabs-items-loaded' : '';
					$cls .= ($items->id == "*") ? ' items-category-all' : ' items-category-' . $items->id;
					$index = $items->id;
					?>
					<div class="ltabs-items <?php echo $cls; ?>">
						<div class="ltabs-items-inner slider-listingtabs products-grid <?php echo $cls_device . ' ';
						echo $cls_animate . ' '; echo $index;?>">
						
							<?php if (!empty($child_items)) { ?>

									<?php include('default_items.php'); ?>
									<script>
										jQuery.noConflict()
										//alert('aaaa');
										var owl = jQuery(".slider-t");
										owl.owlCarousel({
											responsive:{
												0:{
													items:1
												},
												480:{
													items:1
												},
												768:{
													items:1
												},
												992:{
													items:1
												},
												1200:{
													items:1
												}
											},
											margin: 30,
											navigation : true, // Show next and prev buttons
											//autoPlay:true,
											pagination:false,
											stopOnHover:true
										});
									</script>

							<?php } else {?>
								<div class="ltabs-loading"></div>
							<?php } ?>
						</div>
						<?php $classloaded = ($this->_getConfig('source_limit', 2) >= $items->count || $this->_getConfig('source_limit', 2) == 0) ? 'loaded' : ''; ?>
					</div>
				<?php } ?>
				
			</div>
			<!--End Items-->
		</div>
		<?php
		$posttext = $this->_getConfig('posttext');
		if (!empty($posttext)) {
			?>
			<div class="post-text"><?php echo $this->_getConfig('posttext'); ?></div>
		<?php } ?>
	</div>
	<?php include('default_js.phtml'); ?>
<?php
} else {
	echo 'Has no item to show!';
} ?>



