<?php
/*------------------------------------------------------------------------
 # SM Listing Tabs - Version 2.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
if ($this->getReviewsCount()): ?>
	<div class="ratings">
		<?php if ($this->getRatingSummary()): ?>
			<div class="rating-box">
				<div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
			</div>
		<?php endif; ?>
		<p class="rating-links">
			<a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
		</p>
	</div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
	<p class="no-rating"><a title="<?php echo $this->__('Write Your Review') ?>" href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Write Your Review') ?></a></p>
<?php endif; ?>

