<?php
/*------------------------------------------------------------------------
 # SM Shop By - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php if (!$this->getRequest()->isAjax()): ?>
<div id="ajax-errors" style="display: none;">
    <ul class="messages">
        <li class="error-msg">
            <ul>
                <li><span><?php echo $this->__('An error occurred, please try again later.'); ?></span></li>
            </ul>
        </li>
    </ul>
</div>
<div id="loading" style="display: none; margin-bottom: 10px; text-align: center;">
    <img class="v-middle" src="<?php echo $this->getSkinUrl('images/loader-shopby.gif'); ?>" alt="shopby"> <?php echo $this->__('Loading, please wait...'); ?>
</div>
<div id="catalog-listing">
<?php endif; ?>
<div class="category-products">
	<div class="toolbar-top">
		<?php //echo $this->getToolbarHtml() ?>
	</div>
	<div class="yt-products-container clearfix">
		<?php if($this->getMode()!='grid'): ?>
		<?php $_iterator = 0; ?>
		<ol class="products-list" >
			<?php
			$count_input_qty = 0;
			foreach ($_productCollection as $_product):

			$now = date("Y-m-d");
			$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
			$newsTo = substr($_product->getData('news_to_date'), 0, 10);
			$specialprice = $_product->getData('special_price');
			?>
			<li class="item <?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
				<div class="product-list-left">
					<div class="product-image">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
							<?php if($_product->getThumbnail() != $_product->getSmallImage()) { ?>
									<img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270, 384); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									<img class="thumnail-image image-hover" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(270, 384); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								<?php } else { ?>
									<img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270, 384); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								<?php } ?>
						</a>

						<?php if ($newsFrom !="" && $now>=$newsFrom && ($now<=$newsTo || $newsTo=="")){?>
							<div class="new-item">
								<span><?php echo $this->__('New!'); ?></span>
							</div>
						<?php }?>

						<?php if ( $specialprice ){ ?>
							<div class="sale-item">
								<span><?php echo $this->__('Sale'); ?></span>
							</div>
						<?php }?>

					</div>
				</div>
				<div class="product-info">

					<div class="product-name">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>">
							<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
						</a>
					</div>

					<?php //echo $this->getReviewsSummaryHtml($_product, true, true) ?>
					<?php echo $this->getPriceHtml($_product, true) ?>

					<?php
							// Provides extra blocks on which to hang some features for products in the list
							// Features providing UI elements targeting this block will display directly below the product name
							if ($this->getChild('name.after')) {
								$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
								foreach ($_nameAfterChildren as $_nameAfterChildName) {
									$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
									$_nameAfterChild->setProduct($_product);
									echo $_nameAfterChild->toHtml();
								}
							}
					?>

					<?php if($_product->getshort_description()) { ?>
					<div class="product-desciption">
						<?php echo $_product->getshort_description();?>
					</div>
					<?php } ?>

					<div class="product-addto-wrap">
						<div class="product-addcart">
							<?php if($_product->isSaleable()): ?>
								<a class="btn-cart" title="<?php echo $this->__('Add to cart') ?>" href="javascript:void(0);" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
									<?php echo $this->__('Add to cart') ?>
								</a>
							<?php endif; ?>
						</div>
						<div class="wishlist-compare">
							<?php if ( $this->helper('wishlist')->isAllow() ) : ?>
							<a class="link-wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>">
								<?php //echo $this->__('Add to Wishlist') ?>
							</a>
							<?php endif; ?>

							<?php if( $_compareUrl=$this->getAddToCompareUrl($_product) ): ?>

							<a class="link-compare" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare'); ?>">
								<?php //echo $this->__('Add to Compare') ?>
							</a>

							<?php endif;?>
						</div>
					</div>
				</div>
			</li>
			<?php endforeach; ?>
		</ol>
		<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

		<?php else: ?>
		<?php $_collectionSize = $_productCollection->count() ?>
		<?php $_columnCount = $this->getColumnCount();?>

		<?php $i=0; foreach ($_productCollection as $_product):?>
		<?php
		$now = date("Y-m-d");
		$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
		$newsTo = substr($_product->getData('news_to_date'), 0, 10);
		$specialprice = $_product->getData('special_price');
		?>
		<?php if ( $i++ == 0 ){ ?>
		<div class="products-grid">
			<div class="row">
				<?php } ?>
				<div class="item item-wrapper col-lg-3 col-md-3 col-sm-6 col-xs-6">
					<div class="item-inner">

						<div class="product-image">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
								<?php if($_product->getThumbnail() != $_product->getSmallImage()) { ?>
									<img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270, 384); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									<img class="thumnail-image image-hover" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(270, 384); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								<?php } else { ?>
									<img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270, 384); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								<?php } ?>
							</a>
							<?php
							// Provides extra blocks on which to hang some features for products in the list
							// Features providing UI elements targeting this block will display directly below the product name
							if ($this->getChild('name.after')) {
								$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
								foreach ($_nameAfterChildren as $_nameAfterChildName) {
									$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
									$_nameAfterChild->setProduct($_product);
									echo $_nameAfterChild->toHtml();
								}
							}
							?>
							<?php if ($newsFrom !="" && $now>=$newsFrom && ($now<=$newsTo || $newsTo=="")){?>
								<div class="new-item">
									<span><?php echo $this->__('New!'); ?></span>
								</div>
							<?php }?>

							<?php if ( $specialprice ){ ?>
								<div class="sale-item">
									<span><?php echo $this->__('Sale'); ?></span>
								</div>
							<?php }?>
						</div>
						<div class="product_info_price">
                        	<div class="product_info_price_inside">
                            	<?php echo $this->getPriceHtml($_product, true) ?>
                            </div>
                        </div>
						<div class="product-info">
                        	<div class="product-info-inner">
                                <div class="product_other_things">
                                	<ul>
                                    	<li>
                                        	<?php $community = $_product->getCommunity(); ?>
											<?php if($community == "1"){ ?>
                                       		<img src="<?php echo $this->getSkinUrl('images/att/1.jpg') ?>" alt="community" />
                                    		<?php } ?>
                                        </li>
                                        <li>
                                        	<?php $steam = $_product->getSteam(); ?>
											<?php if($steam == "1"){ ?>
                                       		<img src="<?php echo $this->getSkinUrl('images/att/2.gif') ?>" alt="Steam" />
                                    		<?php } ?>
                                        </li>
                                        <li>
                                        	<?php $cdkey = $_product->getCdkey(); ?>
											<?php if($cdkey == "1"){ ?>
                                       		<img src="<?php echo $this->getSkinUrl('images/att/3.gif') ?>" alt="Cd-key" />
                                    		<?php } ?>
                                        </li>
                                        <li>
                                        	<?php $battlenet = $_product->getBattlenet(); ?>
											<?php if($battlenet == "1"){ ?>
                                       		<img src="<?php echo $this->getSkinUrl('images/att/4.gif') ?>" alt="Battlenet" />
                                    		<?php } ?>
                                        </li>
                                        <li>
                                        	<?php $timecard = $_product->getTimecard(); ?>
											<?php if($timecard == "1"){ ?>
                                       		<img src="<?php echo $this->getSkinUrl('images/att/5.jpg') ?>" alt="Time-Card" />
                                    		<?php } ?>
                                        </li>
                                    </ul>

                                </div>
							<div class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name');?>
								</a>
							</div>
							<?php //echo $this->getReviewsSummaryHtml($_product, "short", true); ?>
							<?php echo $this->getPriceHtml($_product, true) ?>

                            <div class="product-addto-wrap">
								<div class="product-addto-wrap-inner">
									<?php if ( $this->helper('wishlist')->isAllow() ) : ?>
										<a class="link-wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>">
											<?php echo $this->__('Add to Wishlist') ?>
										</a>
									<?php endif; ?>

									<div class="product-addcart">
										<?php if($_product->isSaleable()): ?>
											<a class="btn-cart" title="<?php echo $this->__('Buy Now') ?>" href="javascript:void(0);" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
												<?php echo $this->__('Buy Now') ?>
											</a>
										<?php else: ?>
										<p class="availability out-of-stock">
											<span><?php echo $this->__('Out of stock') ?> </span>
										</p>
										<?php endif; ?>
									</div>



									<?php if( $_compareUrl=$this->getAddToCompareUrl($_product) ): ?>
										<a class="link-compare" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare'); ?>">
											<?php echo $this->__('Add to Compare') ?>
										</a>
									<?php endif;?>

								</div>
							</div>
                            </div>
						</div>

					</div>
				</div>
		<?php if ( $i == $_collectionSize ){ ?>
			</div>
		</div>
		<?php } ?>
		<?php endforeach ?>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		<?php endif; ?>
	</div>

	<div class="toolbar-bottom" style="display: none">
		<?php echo $this->getToolbarHtml() ?>
	</div>

</div>
<?php if (!$this->getRequest()->isAjax()): ?>
</div>
<?php endif; ?>
<?php endif; ?>

<?php if ($this->getRequest()->isAjax()): ?>
	<script>
		jQuery(document).ready(function($){
			$(".overwrite-sortby").click(function(){
				$(this).next('ul').toggleClass('active_dropdown');

				$(".limiter-wrap .select-inner ul").removeClass("active_dropdown");
			});

			$(".overwrite-limiter").click(function(){
				$(this).next('ul').toggleClass('active_dropdown');

				$(".sort-by-wrap .select-inner ul").removeClass("active_dropdown");
			});
		});
	</script>
<?php endif; ?>

<?php if ($this->helper('sm_shopby')->isAjaxEnabled() && !$this->getRequest()->isAjax()): ?>

<script type="text/javascript">
    //<![CDATA[
    function pushState(data, link, replace) {
        var History = window.History;
        if ( !History.enabled ) {
            return false;
        }

        if (replace) {
            History.replaceState(data, document.title, link);
        } else {
            History.pushState(data, document.title, link);
        }
    }

    function handleEvent(el, event) {
        var url, fullUrl;
        if (typeof el === 'string') {
            url = el;
        } else if (el.tagName.toLowerCase() === 'a') {
            url = $(el).readAttribute('href');
        } else if (el.tagName.toLowerCase() === 'select') {
            url = $(el).getValue();
        }

        <?php // Add this to query string for full page caching systems ?>
        if (url.indexOf('?') != -1) {
            fullUrl = url + '&isLayerAjax=1';
        } else {
            fullUrl = url + '?isLayerAjax=1';
        }

        $('loading').show();
        $('ajax-errors').hide();

        pushState(null, url, false);

        new Ajax.Request(fullUrl, {
            method: 'get',
            onSuccess: function(transport) {
                if (transport.responseJSON) {
                    $('catalog-listing').update(transport.responseJSON.listing);
                    $('layered-navigation').update(transport.responseJSON.layer);
                    pushState({
                        listing: transport.responseJSON.listing,
                        layer: transport.responseJSON.layer
                    }, url, true);
                    ajaxListener();
                } else {
                    $('ajax-errors').show();
                }
                $('loading').hide();
            }
        });

        if (event) {
            event.preventDefault();
        }
    }
    function ajaxListener() {
        var els;
        els = $$('div.pagination-wrap a').concat(
            $$('div.sort-by-wrap a'),
            $$('div.limiter-wrap a'),
			$$('div.view-mode-wrap a'),
            $$('div.sorter select'),
            $$('div.block-layered-nav a')
        );
        els.each(function(el) {
            if (el.tagName.toLowerCase() === 'a') {
                $(el).observe('click', function(event) {
                    handleEvent(this, event);
                });
            } else if (el.tagName.toLowerCase() === 'select') {
                $(el).setAttribute('onchange', '');
                $(el).observe('change', function(event) {
                    handleEvent(this, event);
                });
            }
        });
    }
    document.observe("dom:loaded", function() {
        ajaxListener();

        (function(History) {
            if ( !History.enabled ) {
                return false;
            }

            pushState({
                listing: $('catalog-listing').innerHTML,
                layer: $('layered-navigation').innerHTML
            }, document.location.href, true);

            // Bind to StateChange Event
            History.Adapter.bind(window, 'popstate', function(event) {
                if (event.type == 'popstate') {
                    var State = History.getState();
                    $('catalog-listing').update(State.data.listing);
                    $('layered-navigation').update(State.data.layer);
                    ajaxListener();
                }
            });
        })(window.History);
    });
    //]]>
</script>
<?php endif; ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
<script type="text/javascript">
    var ias =jQuery.ias({
        container : '.products-grid',
        item: '.item',
        pagination: '.toolbar .pager',
        next: '.next'
//        history: 'false'
    });

    ias.extension(new IASSpinnerExtension({html:'<div><img class="spinner" width="16" src="<?php echo($this->getSkinUrl('images/ajaxscroll/loader.gif')); ?>" /> <span class="spinner">Loading more products, please be patient...</span></div>'}));
    ias.extension(new IASTriggerExtension({offset: 0,text: '<?php echo 'Load more items'; ?>'}));
    ias.extension(new IASNoneLeftExtension({text: 'There are no more pages left to load.'}));
</script>